Adding new intwindow method to TRestDetectorSignalToHitsProcess
rest-for-physics/detectorlib pull request #33
Opened 2022-01-29 17:22 UTC by juanangp

Adding new intwindow method to TRestDetectorSignalToHitsProcess

2022-01-31 14:01 UTC, jgalan commented on src/TRestDetectorHitsEvent.cxx
Lets try new methods get documented. 

Example:
```
///////////////////////////////////////////////
/// \brief This method draws the hits event structure into a TPad.
///
/// This method receives as argument a string that defines the different plots to be produced.
///
/// The following options are allowed:
///
/// * **graph**:
/// * **hist**:
/// * **print**:
///
/// The different options must separated by colons, as "option1:option2:option3".
///
///
/// \return A pointer to the TPad where the event was drawn is returned.
///
```

Also, perhaps arguments could get a default value?

2022-01-31 14:02 UTC, jgalan commented on src/TRestDetectorHitsEvent.cxx
Perhaps this method could re-define few data members, and then we re-call `DrawEvent( string option)`?

2022-01-31 18:22 UTC, juanangp commented on src/TRestDetectorHitsEvent.cxx
I have added new methods to set/get boundaries by replacing previous ones.

2022-01-31 20:28 UTC, jgalan commented
ClassDef from  inc/TRestDetectorSignalToHitsProcess.h should be increased to 4, because there are new members that are written to disk

2022-02-01 16:09 UTC, juanangp commented
> ClassDef from inc/TRestDetectorSignalToHitsProcess.h should be increased to 4, because there are new members that are written to disk

Done

2022-03-16 09:34 UTC, jgalan commented on src/TRestDetectorHitsEvent.cxx
> +  cout<<histOption<<endl;
To be commented //

2022-03-16 09:44 UTC, jgalan commented on src/TRestDetectorHitsEvent.cxx
> -        if (drawEventOption == "hist") this->DrawHistograms(column, pitch, histOption);
The pitch is an option that can be given through argument to control the binSize.

It is defined starting at lines 656 - 640.

It works as follows:

```
ev->DrawEvent("hist[1]")
```
to get a pitch of 1mm.

The default (0.5mm) is defined above:

```
    /// The default histogram using a pitch of 0.5mm
    if (optList.size() == 0) optList.push_back("hist(Cont1,col)[0.5]");
```

Now the pitch is not being used. It is not necessary anymore?

I know documentation is missing, I could write it down, but first lets make sure it should be removed or not.

Note that the `optionStr` may be used at the graphical interface created by `REST_EventViewer` .

The `DrawEvent` method from `Geant4` events was documented recently.

https://sultan.unizar.es/rest/classTRestGeant4Event.html

2022-03-16 09:48 UTC, juanangp commented on src/TRestDetectorHitsEvent.cxx
> -        if (drawEventOption == "hist") this->DrawHistograms(column, pitch, histOption);
The issue that I found is to define a pitch in the Z axis. So, now the pitch is taken from the minimum diff of the hits. However, we can recover old funcionality if you think that should be done like that.

I will document it properly anyhow.

2022-03-16 09:58 UTC, jgalan commented on src/TRestDetectorHitsEvent.cxx
> -        if (drawEventOption == "hist") this->DrawHistograms(column, pitch, histOption);
Ah, if there is a problem in Z, perhaps one needs to define a different pitch for X,Y,Z?

Perhaps we may define internally as `0` by default. If it is `0` we use the method right now, but if we use `[2]` we define the number of bins to adjust for a 2mm pitch?

Inside `TRestGeant4Event::DrawEvent` is implemented as `[binSize=2]` we might have `binSizeX=2,binSizeY=1]`

2022-03-16 10:01 UTC, jgalan commented
Pipeline was not going through because it needed a pull from present master state

2022-03-16 10:18 UTC, juanangp commented on src/TRestDetectorHitsEvent.cxx
> -        if (drawEventOption == "hist") this->DrawHistograms(column, pitch, histOption);
Looks like in `TRestGeant4Event::DrawEvent` still get the same pitch for both axis.

2022-03-16 10:21 UTC, jgalan commented on src/TRestDetectorHitsEvent.cxx
> -        if (drawEventOption == "hist") this->DrawHistograms(column, pitch, histOption);
Yes, I didnt think about a different pitch. I just mention it because of the `pitch=` label. Perhaps is more readable

2022-03-16 10:25 UTC, jgalan commented on src/TRestDetectorHitsEvent.cxx
> -        if (drawEventOption == "hist") this->DrawHistograms(column, pitch, histOption);
Probably the `DrawEvent` method should be common for both, at least for the argument retrieval.

Perhaps, it could be implemented at `TRestEvent::DrawHitsEvent` level the retrieval of options. Then, at `TRestDetectorHitsEvent` and `TRestGeant4Event` we could do:

```
TRestDetectorHitsEvent::DrawEvent( opt )
{
         TRestEvent::DrawHitsEvent( opt );

         // Write now specific drawing 
}

2022-03-16 10:32 UTC, jgalan commented on src/TRestDetectorHitsEvent.cxx
> -        if (drawEventOption == "hist") this->DrawHistograms(column, pitch, histOption);
So, I just created the issue at the framework

2022-03-16 16:24 UTC, jgalan approved these changes

2022-03-16 17:03 UTC, nkx111 approved these changes

2022-03-17 09:49 UTC, lobis commented
So I made a few changes at [7294c8e](https://github.com/rest-for-physics/detectorlib/pull/33/commits/7294c8e6e6430677918f7f84416e41624a116946). They should only be style changes, such as chainging `NULL` to `nullptr`, pasing values as const reference etc. I think everyone should try to make these kind of changes when you happen to modify a file for some other reason.

2022-03-17 09:51 UTC, lobis commented on src/TRestDetectorHitsEvent.cxx
> -Double_t TRestDetectorHitsEvent::GetClosestHitInsideDistanceToPrismBottom(TVector3 x0, TVector3 x1,
We should always try to use const reference! makes no sense to copy the data here, it slows things down.

2022-03-17 09:58 UTC, lobis commented
I re-requested review from @jgalan just in case I broke something, but interestingly the PR can still be merged 🤔

2022-03-17 10:01 UTC, jgalan commented
Why it would break? I let @juanangp to finally merge

2022-03-17 10:03 UTC, juanangp commented
I will do some validation of the changes before merging.

2022-03-17 10:05 UTC, lobis commented
> Why it would break? I let @juanangp to finally merge

Maybe I made a mistake, it wouldn't be the first time 😆

2022-03-17 11:26 UTC, juanangp commented
> > Why it would break? I let @juanangp to finally merge
> 
> Maybe I made a mistake, it wouldn't be the first time 😆

Indeed, it was failing, looks like it doesn't like the const
```
 any GetInputEvent() const { return fSignalEvent; }
```

2022-03-20 17:21 UTC, lobis requested changes
I don't understand some of the changes to the CMakeLists.txt, perhaps we should discuss this in person.

2022-03-20 17:21 UTC, lobis commented on inc/TRestDetectorSignalToHitsProcess.h
> +    any GetInputEvent() { return fSignalEvent; }
Why do you remove `const`?

2022-03-20 17:52 UTC, juanangp commented
About the `const`, I had an error while running an example, looks like there is no virtual funcion `virtual const RESTValue GetInputEvent()` in the base class `TRestEventProcess.h` , we just have:
```
    virtual RESTValue GetInputEvent() = 0;
```
I agree with you that the funcion should be  `const`, so we have two options, we define a `virtual const RESTValue GetInputEvent();` or we move from `virtual RESTValue GetInputEvent() = 0;` on  `TRestEventProcess.h` to  `virtual const RESTValue GetInputEvent();` which would require to change all the inherited functions to  `const`. I would suggest the second and create an issue about this. Same applies to ` GetOutputEvent()`.

About the `CMakeList.txt` this is the best way I found to solve the issue that I had to compile the code with a old Garfield version in sultan and should only affect old Garfield compilations, anyhow, we can have a chat tomorrow.

2022-03-20 17:54 UTC, juanangp commented on inc/TRestDetectorSignalToHitsProcess.h
> +    any GetInputEvent() { return fSignalEvent; }
I would suggest to create an issue about this. I agree it should be `const` but we should have a dedicated issue and a pull request about this. I think this PR is already large enough.

2022-03-31 17:56 UTC, lobis approved these changes

2022-04-21 17:50 UTC, jgalan commented
Please, before merging increase the library version, tag it and add the release notes.

2022-04-26 07:36 UTC, merged